os:
  - osx
language: 
  - objective-c
compiler:
  - clang
before_install:
  - brew update
# libboost needed for spuclib, not spuc_qpsk
install:
  - brew install cmake libboost-dev
before_script:
  - git clone https://github.com/audiofilter/spuclib.git
  - cd spuclib
  - make
  - cd ..
script: make
